# Mini Project 2- Exploring AI Use by Demographic Features

## Using Dataset: Pew Research ATP W152, August 2024

In [37]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

Include cleaned dataset, prepared in `atp-w152.ipynb`

In [38]:
data = pd.read_csv('data/August 2024/atp-w152-clean.csv')

# OLS Regression Models predicting `USEAI_W152_R` likert

Reverse-coded in `atp-w152.ipynb` so higher = more frequent AI use:

- 5	Almost constantly
- 4	Several times a day
- 3	About once a day
- 2	Several times a week
- 1	Less often

Positive coefficients therefore mean *more* frequent AI use; negative coefficients mean *less* frequent.

## OLS Model 1: Income Only

In [39]:
# USEAI_W152_R (Likert 1-5, reverse-coded: higher = more frequent AI use) regressed on household income only
model1 = smf.ols('USEAI_W152_R ~ C(F_INC_SDT1)', data=data).fit()
print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           USEAI_W152_R   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.038
Method:                 Least Squares   F-statistic:                     26.27
Date:                Mon, 25 May 2026   Prob (F-statistic):           3.41e-40
Time:                        20:42:21   Log-Likelihood:                -8679.6
No. Observations:                5118   AIC:                         1.738e+04
Df Residuals:                    5109   BIC:                         1.744e+04
Df Model:                           8
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                1.9950      0.047     42.712      0.000       1.903       2.087
C(F_INC_SDT1)[T.2.0]     0.1271      0.079      1.615      0.106      -0.027       0.281
C(F_INC_SDT1)[T.3.0]     0.1434      0.080      1.790      0.073      -0.014       0.300
C(F_INC_SDT1)[T.4.0]     0.3481      0.083      4.216      0.000       0.186       0.510
C(F_INC_SDT1)[T.5.0]     0.3583      0.083      4.307      0.000       0.195       0.521
C(F_INC_SDT1)[T.6.0]     0.3310      0.083      3.969      0.000       0.168       0.495
C(F_INC_SDT1)[T.7.0]     0.4406      0.089      4.947      0.000       0.266       0.615
C(F_INC_SDT1)[T.8.0]     0.3946      0.087      4.547      0.000       0.224       0.565
C(F_INC_SDT1)[T.9.0]     0.7180      0.056     12.719      0.000       0.607       0.829
==============================================================================
Omnibus:                     4140.171   Durbin-Watson:                   2.017
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              424.323
Skew:                           0.378   Prob(JB):                     7.24e-93
Kurtosis:                       1.809   Cond. No.                         9.02
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## OLS Model 2: Education Only

In [40]:
# USEAI_W152_R regressed on education only
model2 = smf.ols('USEAI_W152_R ~ C(F_EDUCCAT)', data=data).fit()
print(model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           USEAI_W152_R   R-squared:                       0.053
Model:                            OLS   Adj. R-squared:                  0.053
Method:                 Least Squares   F-statistic:                     150.7
Date:                Mon, 25 May 2026   Prob (F-statistic):           2.11e-64
Time:                        20:42:21   Log-Likelihood:                -9053.7
No. Observations:                5364   AIC:                         1.811e+04
Df Residuals:                    5361   BIC:                         1.813e+04
Df Model:                           2
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               2.6867      0.027     98.396      0.000       2.633       2.740
C(F_EDUCCAT)[T.2.0]    -0.3704      0.042     -8.726      0.000      -0.454      -0.287
C(F_EDUCCAT)[T.3.0]    -0.7580      0.044    -17.245      0.000      -0.844      -0.672
==============================================================================
Omnibus:                     2861.353   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              425.417
Skew:                           0.393   Prob(JB):                     4.19e-93
Kurtosis:                       1.866   Cond. No.                         3.38
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## OLS Model 3: Income + Education

In [41]:
# Additive model: income and education together
model3 = smf.ols('USEAI_W152_R ~ C(F_INC_SDT1) + C(F_EDUCCAT)', data=data).fit()
print(model3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           USEAI_W152_R   R-squared:                       0.065
Model:                            OLS   Adj. R-squared:                  0.063
Method:                 Least Squares   F-statistic:                     35.20
Date:                Mon, 25 May 2026   Prob (F-statistic):           3.79e-67
Time:                        20:42:21   Log-Likelihood:                -8605.0
No. Observations:                5114   AIC:                         1.723e+04
Df Residuals:                    5103   BIC:                         1.730e+04
Df Model:                          10
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                2.3994      0.058     41.018      0.000       2.285       2.514
C(F_INC_SDT1)[T.2.0]     0.0678      0.078      0.871      0.384      -0.085       0.221
C(F_INC_SDT1)[T.3.0]     0.0623      0.079      0.785      0.432      -0.093       0.218
C(F_INC_SDT1)[T.4.0]     0.2109      0.082      2.558      0.011       0.049       0.372
C(F_INC_SDT1)[T.5.0]     0.2146      0.083      2.585      0.010       0.052       0.377
C(F_INC_SDT1)[T.6.0]     0.1660      0.084      1.982      0.048       0.002       0.330
C(F_INC_SDT1)[T.7.0]     0.2654      0.089      2.975      0.003       0.091       0.440
C(F_INC_SDT1)[T.8.0]     0.1807      0.088      2.064      0.039       0.009       0.352
C(F_INC_SDT1)[T.9.0]     0.4324      0.061      7.108      0.000       0.313       0.552
C(F_EDUCCAT)[T.2.0]     -0.2758      0.045     -6.083      0.000      -0.365      -0.187
C(F_EDUCCAT)[T.3.0]     -0.5820      0.050    -11.701      0.000      -0.680      -0.484
==============================================================================
Omnibus:                     2120.615   Durbin-Watson:                   2.023
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              378.446
Skew:                           0.380   Prob(JB):                     6.63e-83
Kurtosis:                       1.905   Cond. No.                         10.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## OLS Model 4: Income * Education

In [42]:
# Interaction model: '*' expands to both main effects + the interaction term
model4 = smf.ols('USEAI_W152_R ~ F_INC_SDT1 * F_EDUCCAT', data=data).fit()
print(model4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           USEAI_W152_R   R-squared:                       0.063
Model:                            OLS   Adj. R-squared:                  0.062
Method:                 Least Squares   F-statistic:                     114.2
Date:                Mon, 25 May 2026   Prob (F-statistic):           1.32e-71
Time:                        20:42:21   Log-Likelihood:                -8609.6
No. Observations:                5114   AIC:                         1.723e+04
Df Residuals:                    5110   BIC:                         1.725e+04
Df Model:                           3
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                2.7113      0.114     23.778      0.000       2.488       2.935
F_INC_SDT1               0.0394      0.016      2.448      0.014       0.008       0.071
F_EDUCCAT               -0.3233      0.049     -6.631      0.000      -0.419      -0.228
F_INC_SDT1:F_EDUCCAT     0.0053      0.008      0.683      0.495      -0.010       0.021
==============================================================================
Omnibus:                     2165.205   Durbin-Watson:                   2.027
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              378.312
Skew:                           0.377   Prob(JB):                     7.09e-83
Kurtosis:                       1.901   Cond. No.                         86.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## OLS Model 5: Income + Education + Age + Gender + Race

In [43]:
# Full model: income/education/age as continuous ordinal scales;
# gender and race wrapped in C() since they are nominal categories
model5 = smf.ols(
    'USEAI_W152_R ~ C(F_INC_SDT1) + C(F_EDUCCAT) + C(F_AGECAT) + C(F_GENDER) + C(F_RACECMB)',
    data=data
).fit()
print(model5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           USEAI_W152_R   R-squared:                       0.095
Model:                            OLS   Adj. R-squared:                  0.091
Method:                 Least Squares   F-statistic:                     27.64
Date:                Mon, 25 May 2026   Prob (F-statistic):           4.67e-94
Time:                        20:42:21   Log-Likelihood:                -8402.3
No. Observations:                5043   AIC:                         1.684e+04
Df Residuals:                    5023   BIC:                         1.698e+04
Df Model:                          19
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                2.7929      0.079     35.360      0.000       2.638       2.948
C(F_INC_SDT1)[T.2.0]     0.0557      0.078      0.718      0.473      -0.096       0.208
C(F_INC_SDT1)[T.3.0]     0.0382      0.079      0.484      0.629      -0.117       0.193
C(F_INC_SDT1)[T.4.0]     0.1874      0.082      2.283      0.022       0.026       0.348
C(F_INC_SDT1)[T.5.0]     0.1869      0.083      2.264      0.024       0.025       0.349
C(F_INC_SDT1)[T.6.0]     0.1346      0.084      1.607      0.108      -0.030       0.299
C(F_INC_SDT1)[T.7.0]     0.2123      0.089      2.391      0.017       0.038       0.386
C(F_INC_SDT1)[T.8.0]     0.1534      0.088      1.751      0.080      -0.018       0.325
C(F_INC_SDT1)[T.9.0]     0.3685      0.062      5.921      0.000       0.246       0.491
C(F_EDUCCAT)[T.2.0]     -0.2424      0.045     -5.336      0.000      -0.331      -0.153
C(F_EDUCCAT)[T.3.0]     -0.5338      0.050    -10.661      0.000      -0.632      -0.436
C(F_AGECAT)[T.2.0]      -0.1588      0.057     -2.762      0.006      -0.272      -0.046
C(F_AGECAT)[T.3.0]      -0.3605      0.061     -5.870      0.000      -0.481      -0.240
C(F_AGECAT)[T.4.0]      -0.6175      0.061    -10.080      0.000      -0.738      -0.497
C(F_GENDER)[T.2.0]      -0.1586      0.037     -4.300      0.000      -0.231      -0.086
C(F_GENDER)[T.3.0]      -0.1370      0.237     -0.578      0.564      -0.602       0.328
C(F_RACECMB)[T.2.0]     -0.0511      0.057     -0.901      0.368      -0.162       0.060
C(F_RACECMB)[T.3.0]      0.1058      0.061      1.729      0.084      -0.014       0.226
C(F_RACECMB)[T.4.0]      0.1302      0.086      1.517      0.129      -0.038       0.299
C(F_RACECMB)[T.5.0]     -0.2017      0.095     -2.113      0.035      -0.389      -0.015
==============================================================================
Omnibus:                     1534.138   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              334.466
Skew:                           0.356   Prob(JB):                     2.35e-73
Kurtosis:                       1.959   Cond. No.                         18.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# Summary Table: SE, 95% Confidence Intervals, and p-values across all models

One row per coefficient per model (long/tidy format). Columns: `model`, `term`, standard error (`SE`), the 95% confidence interval bounds (`CI_low`, `CI_high`), and the p-value (`p`). The coefficient (`coef`) is included for context.

In [44]:
# Combine SE, 95% CI, and p-values from every model into one long-format table.
# One row per (model, coefficient).
models = {
    'M1: Income':    model1,
    'M2: Education': model2,
    'M3: Inc+Edu':   model3,
    'M4: Inc*Edu':   model4,
    'M5: Full':      model5,
}

rows = []
for name, res in models.items():
    ci = res.conf_int()
    rows.append(pd.DataFrame({
        'model':   name,
        'term':    res.params.index,
        'coef':    res.params.values,
        'SE':      res.bse.values,
        'CI_low':  ci[0].values,
        'CI_high': ci[1].values,
        'p':       res.pvalues.values,
    }))

summary_table = pd.concat(rows, ignore_index=True).round(3)
summary_table

            model                  term   coef     SE  CI_low  CI_high      p
0      M1: Income             Intercept  1.995  0.047   1.903    2.087  0.000
1      M1: Income  C(F_INC_SDT1)[T.2.0]  0.127  0.079  -0.027    0.281  0.106
2      M1: Income  C(F_INC_SDT1)[T.3.0]  0.143  0.080  -0.014    0.300  0.073
3      M1: Income  C(F_INC_SDT1)[T.4.0]  0.348  0.083   0.186    0.510  0.000
4      M1: Income  C(F_INC_SDT1)[T.5.0]  0.358  0.083   0.195    0.521  0.000
5      M1: Income  C(F_INC_SDT1)[T.6.0]  0.331  0.083   0.168    0.495  0.000
6      M1: Income  C(F_INC_SDT1)[T.7.0]  0.441  0.089   0.266    0.615  0.000
7      M1: Income  C(F_INC_SDT1)[T.8.0]  0.395  0.087   0.224    0.565  0.000
8      M1: Income  C(F_INC_SDT1)[T.9.0]  0.718  0.056   0.607    0.829  0.000
9   M2: Education             Intercept  2.687  0.027   2.633    2.740  0.000
10  M2: Education   C(F_EDUCCAT)[T.2.0] -0.370  0.042  -0.454   -0.287  0.000
11  M2: Education   C(F_EDUCCAT)[T.3.0] -0.758  0.044  -0.844   -0.672  0.000
12    M3: Inc+Edu             Intercept  2.399  0.058   2.285    2.514  0.000
13    M3: Inc+Edu  C(F_INC_SDT1)[T.2.0]  0.068  0.078  -0.085    0.221  0.384
14    M3: Inc+Edu  C(F_INC_SDT1)[T.3.0]  0.062  0.079  -0.093    0.218  0.432
15    M3: Inc+Edu  C(F_INC_SDT1)[T.4.0]  0.211  0.082   0.049    0.372  0.011
16    M3: Inc+Edu  C(F_INC_SDT1)[T.5.0]  0.215  0.083   0.052    0.377  0.010
17    M3: Inc+Edu  C(F_INC_SDT1)[T.6.0]  0.166  0.084   0.002    0.330  0.048
18    M3: Inc+Edu  C(F_INC_SDT1)[T.7.0]  0.265  0.089   0.091    0.440  0.003
19    M3: Inc+Edu  C(F_INC_SDT1)[T.8.0]  0.181  0.088   0.009    0.352  0.039
20    M3: Inc+Edu  C(F_INC_SDT1)[T.9.0]  0.432  0.061   0.313    0.552  0.000
21    M3: Inc+Edu   C(F_EDUCCAT)[T.2.0] -0.276  0.045  -0.365   -0.187  0.000
22    M3: Inc+Edu   C(F_EDUCCAT)[T.3.0] -0.582  0.050  -0.680   -0.484  0.000
23    M4: Inc*Edu             Intercept  2.711  0.114   2.488    2.935  0.000
24    M4: Inc*Edu            F_INC_SDT1  0.039  0.016   0.008    0.071  0.014
25    M4: Inc*Edu             F_EDUCCAT -0.323  0.049  -0.419   -0.228  0.000
26    M4: Inc*Edu  F_INC_SDT1:F_EDUCCAT  0.005  0.008  -0.010    0.021  0.495
27       M5: Full             Intercept  2.793  0.079   2.638    2.948  0.000
28       M5: Full  C(F_INC_SDT1)[T.2.0]  0.056  0.078  -0.096    0.208  0.473
29       M5: Full  C(F_INC_SDT1)[T.3.0]  0.038  0.079  -0.117    0.193  0.629
30       M5: Full  C(F_INC_SDT1)[T.4.0]  0.187  0.082   0.026    0.348  0.022
31       M5: Full  C(F_INC_SDT1)[T.5.0]  0.187  0.083   0.025    0.349  0.024
32       M5: Full  C(F_INC_SDT1)[T.6.0]  0.135  0.084  -0.030    0.299  0.108
33       M5: Full  C(F_INC_SDT1)[T.7.0]  0.212  0.089   0.038    0.386  0.017
34       M5: Full  C(F_INC_SDT1)[T.8.0]  0.153  0.088  -0.018    0.325  0.080
35       M5: Full  C(F_INC_SDT1)[T.9.0]  0.368  0.062   0.246    0.491  0.000
36       M5: Full   C(F_EDUCCAT)[T.2.0] -0.242  0.045  -0.331   -0.153  0.000
37       M5: Full   C(F_EDUCCAT)[T.3.0] -0.534  0.050  -0.632   -0.436  0.000
38       M5: Full    C(F_AGECAT)[T.2.0] -0.159  0.057  -0.272   -0.046  0.006
39       M5: Full    C(F_AGECAT)[T.3.0] -0.360  0.061  -0.481   -0.240  0.000
40       M5: Full    C(F_AGECAT)[T.4.0] -0.617  0.061  -0.738   -0.497  0.000
41       M5: Full    C(F_GENDER)[T.2.0] -0.159  0.037  -0.231   -0.086  0.000
42       M5: Full    C(F_GENDER)[T.3.0] -0.137  0.237  -0.602    0.328  0.564
43       M5: Full   C(F_RACECMB)[T.2.0] -0.051  0.057  -0.162    0.060  0.368
44       M5: Full   C(F_RACECMB)[T.3.0]  0.106  0.061  -0.014    0.226  0.084
45       M5: Full   C(F_RACECMB)[T.4.0]  0.130  0.086  -0.038    0.299  0.129
46       M5: Full   C(F_RACECMB)[T.5.0] -0.202  0.095  -0.389   -0.015  0.035

## Model fit statistics

R-squared, adjusted R-squared, and AIC are model-level summaries (one value per model), so they go in their own table. Number of observations (`N`) is included since it varies across models due to listwise deletion of missing values.

In [45]:
# Model-level fit statistics: R-squared, adjusted R-squared, AIC (one row per model).
fit_stats = pd.DataFrame({
    'model':         list(models.keys()),
    'R-squared':     [res.rsquared for res in models.values()],
    'Adj R-squared': [res.rsquared_adj for res in models.values()],
    'AIC':           [res.aic for res in models.values()],
    'N':             [int(res.nobs) for res in models.values()],
}).round({'R-squared': 3, 'Adj R-squared': 3, 'AIC': 1})

fit_stats

           model  R-squared  Adj R-squared      AIC     N
0     M1: Income      0.040          0.038  17377.3  5118
1  M2: Education      0.053          0.053  18113.4  5364
2    M3: Inc+Edu      0.065          0.063  17232.1  5114
3    M4: Inc*Edu      0.063          0.062  17227.2  5114
4       M5: Full      0.095          0.091  16844.7  5043